/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRiskIndexRouteImport } from './routes/_authenticated/risk/index'
import { Route as AuthenticatedPremiumIndexRouteImport } from './routes/_authenticated/premium/index'
import { Route as AuthenticatedModerationIndexRouteImport } from './routes/_authenticated/moderation/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGeographyIndexRouteImport } from './routes/_authenticated/geography/index'
import { Route as AuthenticatedCommunicationIndexRouteImport } from './routes/_authenticated/communication/index'
import { Route as AuthenticatedActivitiesIndexRouteImport } from './routes/_authenticated/activities/index'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedRiskFraudRouteImport } from './routes/_authenticated/risk/fraud'
import { Route as AuthenticatedRiskDisputesRouteImport } from './routes/_authenticated/risk/disputes'
import { Route as AuthenticatedPremiumAnalysisRouteImport } from './routes/_authenticated/premium/analysis'
import { Route as AuthenticatedModerationIdRouteImport } from './routes/_authenticated/moderation/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedActivitiesGhostRouteImport } from './routes/_authenticated/activities/ghost'
import { Route as AuthenticatedActivitiesIdRouteImport } from './routes/_authenticated/activities/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRiskIndexRoute = AuthenticatedRiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumIndexRoute =
  AuthenticatedPremiumIndexRouteImport.update({
    id: '/premium/',
    path: '/premium/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationIndexRoute =
  AuthenticatedModerationIndexRouteImport.update({
    id: '/moderation/',
    path: '/moderation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGeographyIndexRoute =
  AuthenticatedGeographyIndexRouteImport.update({
    id: '/geography/',
    path: '/geography/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationIndexRoute =
  AuthenticatedCommunicationIndexRouteImport.update({
    id: '/communication/',
    path: '/communication/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRiskFraudRoute = AuthenticatedRiskFraudRouteImport.update({
  id: '/risk/fraud',
  path: '/risk/fraud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskDisputesRoute =
  AuthenticatedRiskDisputesRouteImport.update({
    id: '/risk/disputes',
    path: '/risk/disputes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiumAnalysisRoute =
  AuthenticatedPremiumAnalysisRouteImport.update({
    id: '/premium/analysis',
    path: '/premium/analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationIdRoute =
  AuthenticatedModerationIdRouteImport.update({
    id: '/moderation/$id',
    path: '/moderation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesGhostRoute =
  AuthenticatedActivitiesGhostRouteImport.update({
    id: '/activities/ghost',
    path: '/activities/ghost',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesIdRoute =
  AuthenticatedActivitiesIdRouteImport.update({
    id: '/activities/$id',
    path: '/activities/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/activities/ghost': typeof AuthenticatedActivitiesGhostRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/moderation/$id': typeof AuthenticatedModerationIdRoute
  '/premium/analysis': typeof AuthenticatedPremiumAnalysisRoute
  '/risk/disputes': typeof AuthenticatedRiskDisputesRoute
  '/risk/fraud': typeof AuthenticatedRiskFraudRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/communication': typeof AuthenticatedCommunicationIndexRoute
  '/geography': typeof AuthenticatedGeographyIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/moderation': typeof AuthenticatedModerationIndexRoute
  '/premium': typeof AuthenticatedPremiumIndexRoute
  '/risk': typeof AuthenticatedRiskIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/activities/ghost': typeof AuthenticatedActivitiesGhostRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/moderation/$id': typeof AuthenticatedModerationIdRoute
  '/premium/analysis': typeof AuthenticatedPremiumAnalysisRoute
  '/risk/disputes': typeof AuthenticatedRiskDisputesRoute
  '/risk/fraud': typeof AuthenticatedRiskFraudRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/communication': typeof AuthenticatedCommunicationIndexRoute
  '/geography': typeof AuthenticatedGeographyIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/moderation': typeof AuthenticatedModerationIndexRoute
  '/premium': typeof AuthenticatedPremiumIndexRoute
  '/risk': typeof AuthenticatedRiskIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/_authenticated/activities/ghost': typeof AuthenticatedActivitiesGhostRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/moderation/$id': typeof AuthenticatedModerationIdRoute
  '/_authenticated/premium/analysis': typeof AuthenticatedPremiumAnalysisRoute
  '/_authenticated/risk/disputes': typeof AuthenticatedRiskDisputesRoute
  '/_authenticated/risk/fraud': typeof AuthenticatedRiskFraudRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/_authenticated/communication/': typeof AuthenticatedCommunicationIndexRoute
  '/_authenticated/geography/': typeof AuthenticatedGeographyIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/moderation/': typeof AuthenticatedModerationIndexRoute
  '/_authenticated/premium/': typeof AuthenticatedPremiumIndexRoute
  '/_authenticated/risk/': typeof AuthenticatedRiskIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/activities/$id'
    | '/activities/ghost'
    | '/errors/$error'
    | '/moderation/$id'
    | '/premium/analysis'
    | '/risk/disputes'
    | '/risk/fraud'
    | '/settings/account'
    | '/settings/appearance'
    | '/users/$id'
    | '/activities'
    | '/communication'
    | '/geography'
    | '/help-center'
    | '/moderation'
    | '/premium'
    | '/risk'
    | '/settings/'
    | '/system'
    | '/tasks'
    | '/transactions'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/activities/$id'
    | '/activities/ghost'
    | '/errors/$error'
    | '/moderation/$id'
    | '/premium/analysis'
    | '/risk/disputes'
    | '/risk/fraud'
    | '/settings/account'
    | '/settings/appearance'
    | '/users/$id'
    | '/activities'
    | '/communication'
    | '/geography'
    | '/help-center'
    | '/moderation'
    | '/premium'
    | '/risk'
    | '/settings'
    | '/system'
    | '/tasks'
    | '/transactions'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/activities/$id'
    | '/_authenticated/activities/ghost'
    | '/_authenticated/errors/$error'
    | '/_authenticated/moderation/$id'
    | '/_authenticated/premium/analysis'
    | '/_authenticated/risk/disputes'
    | '/_authenticated/risk/fraud'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/users/$id'
    | '/_authenticated/activities/'
    | '/_authenticated/communication/'
    | '/_authenticated/geography/'
    | '/_authenticated/help-center/'
    | '/_authenticated/moderation/'
    | '/_authenticated/premium/'
    | '/_authenticated/risk/'
    | '/_authenticated/settings/'
    | '/_authenticated/system/'
    | '/_authenticated/tasks/'
    | '/_authenticated/transactions/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/risk/': {
      id: '/_authenticated/risk/'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium/': {
      id: '/_authenticated/premium/'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation/': {
      id: '/_authenticated/moderation/'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geography/': {
      id: '/_authenticated/geography/'
      path: '/geography'
      fullPath: '/geography'
      preLoaderRoute: typeof AuthenticatedGeographyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication/': {
      id: '/_authenticated/communication/'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/': {
      id: '/_authenticated/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/risk/fraud': {
      id: '/_authenticated/risk/fraud'
      path: '/risk/fraud'
      fullPath: '/risk/fraud'
      preLoaderRoute: typeof AuthenticatedRiskFraudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk/disputes': {
      id: '/_authenticated/risk/disputes'
      path: '/risk/disputes'
      fullPath: '/risk/disputes'
      preLoaderRoute: typeof AuthenticatedRiskDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium/analysis': {
      id: '/_authenticated/premium/analysis'
      path: '/premium/analysis'
      fullPath: '/premium/analysis'
      preLoaderRoute: typeof AuthenticatedPremiumAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation/$id': {
      id: '/_authenticated/moderation/$id'
      path: '/moderation/$id'
      fullPath: '/moderation/$id'
      preLoaderRoute: typeof AuthenticatedModerationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/ghost': {
      id: '/_authenticated/activities/ghost'
      path: '/activities/ghost'
      fullPath: '/activities/ghost'
      preLoaderRoute: typeof AuthenticatedActivitiesGhostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/$id': {
      id: '/_authenticated/activities/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof AuthenticatedActivitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivitiesIdRoute: typeof AuthenticatedActivitiesIdRoute
  AuthenticatedActivitiesGhostRoute: typeof AuthenticatedActivitiesGhostRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedModerationIdRoute: typeof AuthenticatedModerationIdRoute
  AuthenticatedPremiumAnalysisRoute: typeof AuthenticatedPremiumAnalysisRoute
  AuthenticatedRiskDisputesRoute: typeof AuthenticatedRiskDisputesRoute
  AuthenticatedRiskFraudRoute: typeof AuthenticatedRiskFraudRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
  AuthenticatedCommunicationIndexRoute: typeof AuthenticatedCommunicationIndexRoute
  AuthenticatedGeographyIndexRoute: typeof AuthenticatedGeographyIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedModerationIndexRoute: typeof AuthenticatedModerationIndexRoute
  AuthenticatedPremiumIndexRoute: typeof AuthenticatedPremiumIndexRoute
  AuthenticatedRiskIndexRoute: typeof AuthenticatedRiskIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivitiesIdRoute: AuthenticatedActivitiesIdRoute,
  AuthenticatedActivitiesGhostRoute: AuthenticatedActivitiesGhostRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedModerationIdRoute: AuthenticatedModerationIdRoute,
  AuthenticatedPremiumAnalysisRoute: AuthenticatedPremiumAnalysisRoute,
  AuthenticatedRiskDisputesRoute: AuthenticatedRiskDisputesRoute,
  AuthenticatedRiskFraudRoute: AuthenticatedRiskFraudRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
  AuthenticatedCommunicationIndexRoute: AuthenticatedCommunicationIndexRoute,
  AuthenticatedGeographyIndexRoute: AuthenticatedGeographyIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedModerationIndexRoute: AuthenticatedModerationIndexRoute,
  AuthenticatedPremiumIndexRoute: AuthenticatedPremiumIndexRoute,
  AuthenticatedRiskIndexRoute: AuthenticatedRiskIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
