-- 创建应用用户（如果指定了）
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${POSTGRES_APP_USER:-app}') THEN
        CREATE USER ${POSTGRES_APP_USER:-app} WITH PASSWORD '${POSTGRES_APP_PASSWORD:-app_password}';
        GRANT CONNECT ON DATABASE ${POSTGRES_DB:-postgres} TO ${POSTGRES_APP_USER:-app};
        GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER:-app};
        GRANT CREATE ON SCHEMA public TO ${POSTGRES_APP_USER:-app};
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${POSTGRES_APP_USER:-app};
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_APP_USER:-app};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRES_APP_USER:-app};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_APP_USER:-app};
    END IF;
END
$$;
